In [1]:
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [2]:
A = np.array([[1,2,3], [4,5,6]])
A.shape

B = np.array([[1,2], [3,4], [5,6]])
B.shape

np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [3]:
X = np.array([1,2])
X.shape

W = np.array([[1,3,5], [2,4,6]])
print(W)
W.shape

Y = np.dot(X, W)
print(Y)

[[1 3 5]
 [2 4 6]]
[ 5 11 17]
